{{- if and (eq .Values.provider "bitwarden") .Values.adminCredentialsBitwardenID }}
---
# secret gotosocial email stuff
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smol-os-credentials
  namespace: smol-os
spec:
  target:
    # Name of the kubernetes secret
    name: smol-os-credentials
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # Key-names within the kubernetes secret
        password: |-
          {{ `{{ .password }}` }}

  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        # key-id of the bitwarden secret
        key: {{ .Values.adminCredentialsBitwardenID }}
        # property within the bitwarden secret we want
        property: password
{{- end }}
