################################################################################
# ____                  _             ___     ___
#/ ___|  ___ _ ____   _(_) ___ ___   ( _ )   |_ _|_ __   __ _ _ __ ___  ___ ___
#\___ \ / _ \ '__\ \ / / |/ __/ _ \  / _ \/\  | || '_ \ / _` | '__/ _ \/ __/ __|
# ___) |  __/ |   \ V /| | (_|  __/ | (_>  <  | || | | | (_| | | |  __/\__ \__ \
#|____/ \___|_|    \_/ |_|\___\___|  \___/\/ |___|_| |_|\__, |_|  \___||___/___/
#                                                       |___/
################################################################################
# -- Service cinfiguration. Used to expose VM to the outside world.
# Accepts a list of ports to open.
service:
  - name: test-service
    type: LoadBalancer
    externalTrafficPolicy: null
    ports:
      - name: ssh
        port: 22
        targetPort: 22
        protocol: TCP
      - name: vnc
        port: 5900
        targetPort: 5900
        protocol: TCP
      - name: rdp
        nodePort: 31597
        port: 3389
        protocol: TCP
        targetPort: 3389
      - name: sunshine0
        port: 47984
        protocol: TCP
        targetPort: 47984
      - name: sunshine1
        port: 47985
        protocol: TCP
        targetPort: 47985
      - name: sunshine2
        port: 47986
        protocol: TCP
        targetPort: 47986
      - name: sunshine3
        port: 47987
        protocol: TCP
        targetPort: 47987
      - name: sunshine4
        port: 47988
        protocol: TCP
        targetPort: 47988
      - name: sunshine5
        port: 47989
        protocol: TCP
        targetPort: 47989
      - name: sunshine6
        port: 47990
        protocol: TCP
        targetPort: 47990
      - name: sunshine7
        port: 47998
        protocol: UDP
        targetPort: 47998
      - name: sunshine8
        port: 47999
        protocol: UDP
        targetPort: 47999
      - name: sunshine9
        port: 48000
        protocol: UDP
        targetPort: 48000
      - name: sunshine10
        port: 48010
        protocol: TCP
        targetPort: 48010
# -- Ingress configuration
ingress:
  enabled: false
  className: "nginx"
  hostname: "novnc.buildstar.online"
  annotations: {}
  #  cert-manager.io/cluster-issuer: "letsencrypt-staging"
  tls: []
  #  enabled: true
  #  secretName: "tls-kubevirt-manager"
  # paths:
  # - path: /
  #   pathType: Prefix
  #   backend:
  #     service:
  #       name: test-service
  #       port:
  #         number: 8080
