---
# secret gotosocial email stuff
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smol-os-credentials
  namespace: smol-os
spec:
  target:
    # Name of the kubernetes secret
    name: smol-os-credentials
    namespace: smol-os
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # Key-names within the kubernetes secret
        password |-
          {{ `{{ .username }}` }}
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        # key-id of the bitwarden secret
        key: bceb4206-9a61-47c1-8bcb-b339012f0c26
        # property within the bitwarden secret we want
        property: password
